[phases.setup]
nixPkgs = ["nodejs_18"]

[phases.install]
cmds = [
  "cd pet-app && npm install",
  "cd pet-app-server && npm install"
]

[phases.build]
cmds = [
  "cd pet-app && npm run build:h5",
  "mkdir -p pet-app-server/public",
  "cp -r pet-app/dist/build/h5/* pet-app-server/public/"
]

[start]
cmd = "cd pet-app-server && npm start"
